action_items|id uuid NN, minutes_id uuid NN, description text NN, assigned_to varchar, due_date date, status varchar D='pending', created_at timestamptz D=now(), updated_at timestamptz D=now()
audit_logs|id uuid NN, super_admin_id uuid NN, action varchar NN, target_user_id uuid, target_member_id uuid, details jsonb, ip_address varchar, created_at timestamptz D=now()
b2c_transactions|id uuid NN, withdrawal_id uuid NN, mpesa_transaction_id text NN, phone_number text NN, amount numeric NN, status text NN D='initiated', initiated_at timestamptz NN D=now(), completed_at timestamptz, error_message text, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now(), mpesa_charge numeric NN D=0, working_account_balance numeric, utility_account_balance numeric, recipient_name text, wallet_type text NN D='penalty', transaction_completed_at timestamptz
bank_transactions|id uuid NN, member_id uuid, phone text NN, name text, amount numeric NN, transaction_date date NN, month int4 NN, year int4 NN, transaction_reference text NN, mpesa_code text, raw_details text, created_at timestamptz NN D=now()
beneficiaries|id uuid NN, member_id uuid NN, name text NN, relationship text NN D='spouse', phone text, id_number text, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
beneficiary_requests|id uuid NN, member_id uuid NN, request_type varchar NN, status varchar D='pending', beneficiary_name varchar, beneficiary_relationship varchar, beneficiary_phone varchar, beneficiary_id_number varchar, beneficiary_id uuid, reason text NN, admin_notes text, reviewed_by uuid, reviewed_at timestamptz, created_at timestamptz D=now(), updated_at timestamptz D=now()
book_balance|id uuid NN, transaction_date date NN, check_number varchar NN, debit numeric NN, book_balance numeric NN, reason text, created_by uuid NN, created_at timestamptz D=now(), updated_at timestamptz D=now()
contributions|id uuid NN, member_id uuid NN, amount numeric NN, month int4 NN, year int4 NN, due_date date NN, paid_date date, status text NN D='pending', payment_id uuid, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
conversation_participants|id uuid NN, conversation_id uuid NN, user_id uuid NN, joined_at timestamptz NN D=now(), last_read_at timestamptz NN D=now()
conversations|id uuid NN, type text NN D='private', name text, created_by uuid NN, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
dashboard_security|id uuid NN, user_id uuid NN, pin_hash text, webauthn_credential_id text, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
documents|id uuid NN, member_id uuid NN, file_name text NN, file_type text NN D='other', file_url text NN, uploaded_by uuid NN, status text NN D='pending', notes text, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
donation_campaigns|id uuid NN, title text NN, description text, amount numeric NN, active bool NN D=true, created_by uuid, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now(), goal_type text NN D='fixed', target_total numeric, allow_partial bool NN D=true
donation_payment_records|id uuid NN, campaign_id uuid, member_id uuid, amount numeric NN, status text NN D='pending', mpesa_transaction_id text, payment_ref text, created_at timestamptz NN D=now(), verified_at timestamptz, updated_at timestamptz NN D=now()
donation_wallet|id uuid NN, total_balance numeric NN D=0, total_received numeric NN D=0, total_withdrawn numeric NN D=0, updated_at timestamptz NN D=now()
donation_withdrawal_signatories|id uuid NN, withdrawal_id uuid, signatory_role text NN, signatory_user_id uuid, status text NN D='pending', signature_url text, approved_at timestamptz, rejected_at timestamptz, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now(), rejection_reason text
donation_withdrawals|id uuid NN, amount numeric NN, reason text NN, status text NN D='pending', requested_by uuid, submitted_at timestamptz NN D=now(), created_at timestamptz NN D=now(), updated_at timestamptz NN D=now(), phone_number text
events|id uuid NN, title text NN, description text, event_type text NN D='funeral', departed_name text, relationship text D='member', related_member_id uuid, contribution_amount numeric NN D=0, status text NN D='active', created_by uuid NN, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now(), scheduled_date timestamptz, rescheduled_date timestamptz, reschedule_reason text
executive_badges|id uuid NN, role_name text NN, badge_url text, description text, created_by uuid, updated_by uuid, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
expenses|id uuid NN, expense_type varchar NN, category varchar NN, amount numeric NN, description text, recipient_name varchar, recipient_member_id uuid, payment_method varchar, reference_number varchar, status varchar D='pending', approved_by uuid, approved_at timestamptz, paid_by uuid, paid_at timestamptz, created_by uuid NN, created_at timestamptz D=now(), updated_at timestamptz D=now(), wallet_type text NN D='operational', withdrawal_id uuid, withdrawal_table text, mpesa_charge numeric NN D=0, phone_number text
financial_reports|id uuid NN, report_type varchar NN, report_period_start date NN, report_period_end date NN, total_contributions numeric D=0, total_expenses numeric D=0, total_payouts numeric D=0, net_balance numeric D=0, report_data jsonb, generated_by uuid NN, generated_at timestamptz D=now()
meeting_attendance|id uuid NN, meeting_id uuid NN, user_id uuid NN, status text NN, created_at timestamptz D=now(), updated_at timestamptz D=now()
meeting_minutes|id uuid NN, created_by uuid NN, meeting_date date NN, meeting_type varchar NN D='general', title varchar NN, attendees _text, agenda text, decisions text, action_items text, next_meeting_date date, status varchar D='draft', created_at timestamptz D=now(), updated_at timestamptz D=now(), discussions text, absent_with_apology _text, absent_without_apology _text, visible_to_members _text, rejection_notes text, submitted_by uuid, submitted_at timestamptz, reviewed_by uuid, reviewed_at timestamptz, chairperson_signature_url text, secretary_signature_url text, chairperson_name varchar, secretary_name varchar, secretary_reviewed_by uuid, secretary_reviewed_at timestamptz, secretary_notes text
member_access_logs|id uuid NN, super_admin_id uuid NN, member_id uuid NN, access_type varchar NN, reason text, created_at timestamptz D=now()
member_registrations|id uuid NN, full_name text NN, phone_number text NN, department text, working_location text, date_of_birth date, status text NN D='payment_pending', payment_status text NN D='unpaid', approved_at timestamptz, approved_by uuid, approval_notes text, rejection_reason text, verified_at timestamptz, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
members|id uuid NN, user_id uuid, name text NN, phone text NN, member_id text, total_contributions numeric NN D=0, total_penalties numeric NN D=0, is_active bool NN D=true, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now(), profile_picture_url text, status_message text D='Hey there! I am using Welfare App', status text NN D='active'
memo_recipients|id uuid NN, memo_id uuid NN, member_id uuid NN, delivered_at timestamptz, seen_at timestamptz, downloaded_at timestamptz, created_at timestamptz D=now()
memo_templates|id uuid NN, name varchar NN, category varchar NN, template_content text NN, variables jsonb, created_by uuid NN, created_at timestamptz D=now(), updated_at timestamptz D=now()
memos|id uuid NN, reference_number varchar, title varchar NN, category varchar NN, content text NN, recipient_type varchar NN, status varchar D='draft', attachments _text, created_by uuid NN, created_at timestamptz D=now(), sent_at timestamptz, updated_at timestamptz D=now()
message_reactions|id uuid NN, message_id uuid NN, user_id uuid NN, emoji text NN, created_at timestamptz NN D=now()
messages|id uuid NN, user_id uuid NN, member_id uuid, content text NN, created_at timestamptz NN D=now(), conversation_id uuid, reply_to_id uuid, status text NN D='sent', attachment_url text, attachment_type text, attachment_name text, edited_at timestamptz
news|id uuid NN, title text NN, content text NN, author_id uuid NN, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now(), scheduled_date timestamptz, rescheduled_date timestamptz, reschedule_reason text, status text D='active'
news_read|id uuid NN, news_id uuid NN, user_id uuid NN, read_at timestamptz D=now()
notifications|id uuid NN, user_id uuid NN, title text NN, message text NN, is_read bool NN D=false, type text NN D='info', created_at timestamptz NN D=now()
office_bearer_signatures|id uuid NN, role varchar NN, signature_url text, updated_by uuid, updated_at timestamptz D=now()
operational_payment_records|id uuid NN, member_id uuid, amount numeric NN, source text NN D='stk_push', status text NN D='pending', mpesa_transaction_id text, payment_ref text, notes text, created_by uuid, verified_at timestamptz, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
operational_wallet|id uuid NN, total_received numeric NN D=0, total_withdrawn numeric NN D=0, total_balance numeric NN D=0, updated_at timestamptz NN D=now()
operational_withdrawal_signatories|id uuid NN, withdrawal_id uuid, signatory_role text NN, signatory_user_id uuid, status text NN D='pending', signature_url text, approved_at timestamptz, rejected_at timestamptz, rejection_reason text, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
operational_withdrawals|id uuid NN, amount numeric NN, reason text NN, category text NN D='payout', expense_type text, recipient_name text, phone_number text, requested_by uuid, status text NN D='pending', submitted_at timestamptz NN D=now(), created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
organization_settings|id uuid NN, organization_name varchar NN D='KHCWW', organization_address text, organization_email varchar, organization_phone varchar, logo_url text, signature_url text, stamp_url text, letterhead_template text, payout_rules jsonb, updated_by uuid, updated_at timestamptz D=now()
password_resets|id uuid NN, user_id uuid NN, reset_token varchar NN, reset_by uuid, reset_at timestamptz, new_password_hash varchar, created_at timestamptz D=now(), expires_at timestamptz, reason text
payments|id uuid NN, member_id uuid, amount numeric NN, transaction_ref text, source text NN D='bank_sms', matched bool NN D=false, raw_message text, received_at timestamptz NN D=now(), created_at timestamptz NN D=now()
payouts|id uuid NN, member_id uuid NN, payout_type varchar NN, amount numeric NN, eligible_amount numeric NN, reason text, supporting_documents _text, status varchar D='pending', approved_by uuid, approved_at timestamptz, paid_by uuid, paid_at timestamptz, payment_reference varchar, rejection_reason text, created_by uuid NN, created_at timestamptz D=now(), updated_at timestamptz D=now()
penalties|id uuid NN, member_id uuid NN, contribution_id uuid, amount numeric NN, reason text NN D='Late payment', is_paid bool NN D=false, created_at timestamptz NN D=now()
penalty_payment_records|id uuid NN, member_id uuid NN, penalty_id uuid, amount numeric NN, payment_ref text, mpesa_transaction_id text, status text NN D='pending', verified_by uuid, verified_at timestamptz, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
penalty_payments|id uuid NN, member_id uuid NN, amount numeric NN, reference_number text NN, payment_date date NN, status text NN D='pending', verified_by uuid, verified_at timestamptz, rejection_reason text, notes text, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now(), payment_message text
penalty_wallet|id uuid NN, total_balance numeric NN D=0, total_received numeric NN D=0, total_withdrawn numeric NN D=0, last_updated timestamptz NN D=now(), created_at timestamptz NN D=now()
penalty_withdrawals|id uuid NN, amount numeric NN, reason text NN, phone_number text, requested_by uuid NN, status enum40 NN D='pending', submitted_at timestamptz, completed_at timestamptz, receipt_url text, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
push_tokens|id uuid NN, user_id uuid NN, token text NN, platform text, user_agent text, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
registration_access_links|id uuid NN, registration_id uuid NN, access_token text NN, temporary_password text, used bool NN D=false, expires_at timestamptz NN, created_at timestamptz NN D=now()
registration_config|id uuid NN, retiring_date date, registration_fee numeric NN D=1000, active bool NN D=true, show_on_login bool NN D=true, auto_approve bool NN D=false, updated_by uuid, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
registration_fees|id uuid NN, registration_id uuid NN, amount numeric NN, phone_number text, mpesa_checkout_request_id text, mpesa_transaction_id text, status text NN D='pending', retry_count int4 NN D=0, error_message text, last_retry_at timestamptz, verified_at timestamptz, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
signatory_signatures|id uuid NN, user_id uuid NN, signatory_role text NN, signature_url text, full_name text, updated_by uuid, updated_at timestamptz NN D=now(), created_at timestamptz NN D=now()
sms_logs|id uuid NN, recipient_phone text NN, message text NN, status text NN D='pending', provider_ref text, created_at timestamptz NN D=now()
system_health|id uuid NN, metric_name varchar NN, metric_value numeric, status varchar, details jsonb, checked_at timestamptz D=now()
system_logs|id uuid NN, log_level varchar NN, component varchar, message text NN, error_details jsonb, user_id uuid, request_path varchar, status_code int4, created_at timestamptz D=now(), resolved bool D=false, resolved_by uuid, resolved_at timestamptz
unmatched_payments|id uuid NN, payment_id uuid NN, raw_message text, extracted_phone text, extracted_amount numeric, resolved bool NN D=false, resolved_by uuid, resolved_at timestamptz, created_at timestamptz NN D=now()
user_presence|id uuid NN, user_id uuid NN, is_online bool NN D=false, last_seen timestamptz NN D=now()
user_roles|id uuid NN, user_id uuid NN, role enum40 NN, is_active bool D=true
wallet_transactions|id uuid NN, wallet_type text NN, direction text NN, source text NN, reference_id uuid, reference_table text, party_name text, party_phone text, gross_amount numeric NN D=0, mpesa_charge numeric NN D=0, system_fee numeric NN D=0, net_amount numeric NN D=0, running_balance numeric NN D=0, mpesa_receipt text, status text NN D='completed', notes text, created_by uuid, occurred_at timestamptz NN D=now(), created_at timestamptz NN D=now()
welfare_settings|id uuid NN, name text NN D='Welfare Group', monthly_contribution_amount numeric NN D=500, contribution_due_day int4 NN D=5, penalty_amount numeric NN D=100, penalty_grace_days int4 NN D=7, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
withdrawal_receipts|id uuid NN, withdrawal_id uuid NN, receipt_pdf_url text NN, generated_at timestamptz NN D=now(), created_at timestamptz NN D=now()
withdrawal_signatories|id uuid NN, withdrawal_id uuid NN, signatory_role text NN, signatory_user_id uuid, status enum40 NN D='pending', signature_url text, rejection_reason text, approved_at timestamptz, rejected_at timestamptz, created_at timestamptz NN D=now(), updated_at timestamptz NN D=now()
